//! Libraries
import type { Metadata } from "next";

//! CSS
import "./globals.css";

export const metadata: Metadata = {
  title: "Authentication Form",
  description: "Generated by next and tailwind",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
